name: medical_translator_app
description: "Medical Translator App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  uuid: ^4.1.0
  equatable: ^2.0.5
  intl: ^0.18.0
  
  # Firebase
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.2
  firebase_database: ^10.3.7
  
  # Speech & Translation - FIXED VERSION
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.3
  translator: ^0.1.7
  
  # Permissions & Media
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # Drawing
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
